<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
    <PublicSign>false</PublicSign>
    <AssemblyName>Cassandra.IntegrationTests</AssemblyName>
    <AssemblyOriginatorKeyFile>../../build/datastax.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PackageId>Cassandra.IntegrationTests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cassandra\Cassandra.csproj" />
    <ProjectReference Include="..\Extensions\Cassandra.AppMetrics\Cassandra.AppMetrics.csproj" />
    <ProjectReference Include="..\Cassandra.Tests\Cassandra.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="App.Metrics" Version="3.2.0" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" Version="1.5.1" />
    <PackageReference Include="SSH.NET" Version="2020.0.2" />
    <PackageReference Include="Appveyor.TestLogger" Version="2.0.0" />
    <PackageReference Include="Microsoft.DotNet.InternalAbstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.7.99" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="NunitXml.TestLogger" Version="2.1.41" />
    <PackageReference Include="System.Runtime.Serialization.Json" Version="4.0.2" />
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.1.1" />
    <PackageReference Include="XunitXml.TestLogger" Version="2.1.26" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Extensions\Cassandra.OpenTelemetry\Cassandra.OpenTelemetry.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>